### ISSUE TITLE
Is it possible to convert windows emoji to apple emoji using your library?

### ISSUE THREAD

**Issue by VadimChorrny** [tommoor/react-emoji-render#100]
**I work on Windows**, I write posts in the project through **markdown**, <br>
I insert **Windows emoji** there, <br>
**I would like to convert emoji to apple style at the output in markdown files**, <br>
**as Telegram does**

**GIF how it works in Telegram**
https://imgur.com/a/dq2fzTq

**My code where I convert markdown to html**
https://github.com/1alexvash/AlexCodeBlog/blob/master/helpers/markdownToHtml.ts

**Comment by enzoferey** [comment]
Hey @VadimChorrny ! Very good question, I actually have no idea how Telegram implemented that feature. Emojis unicodes display based on your OS, so my first thought is that they are transforming Windows emojis to images of the Apple's ones. However, I just had a look at https://web.telegram.org/ and I can see plain emojis in the source HTML. Maybe it's because I'm on MacOS so they don't need to do the conversion, I don't know.

Please check on your side how the HTML code looks like and we will see if there is any possible way of doing so.

**Comment by VadimChorrny** [comment]
> 
I checked on **macOS** and **Windows**.
On **macOS**, I got emojis from **Apple**.
And on **Windows**, I got emojis from **Windows**.

_Unfortunately, I didn't get the result I wanted (_

**Comment by enzoferey** [comment]
That's the expected behaviour @VadimChorrny as I wrote above:

> Emojis unicodes display based on your OS

Please check on Windows the Telegram web HTML elements to see how the Windows emojis you write are being displayed as Apple emojis. We might be able to take some hints from that.
