### ISSUE TITLE
Most flags not rendering when using shortcodes

### ISSUE THREAD

**Issue by joshbeitler** [tommoor/react-emoji-render#42]
See this sandbox: https://codesandbox.io/s/fancy-morning-jm198

Flag emojis using the Slack-style shorthand (e.g.: `:flag-us`, `:flag-mx`) don't seem to render using either `toArray` or the built-in Emoji components. They do appear to be in the `aliases.js` file, so I'm not sure why these ones don't work. Without the `flag-` prefix, some do seem to work (e.g. :`:us:`).

**Comment by enzoferey** [comment]
Hi @joshbeitler !

It looks like you have 2 issues:

1) You are not using the latest version of `react-emoji-render`, we added some aliases since the `v0.6.0` (for example :flag-mx:).
2) In our [aliases.js](https://github.com/tommoor/react-emoji-render/blob/master/data/aliases.js) I cannot find any reference to `:flag-us:` not `:flag-jp:`, so it's normal that they don't work. Feel free to open a PR with them 👍

**Comment by joshbeitler** [comment]
@enzoferey Thanks! You're totally right, my bad. I had copied a sandbox from a previous issue I saw on here, must've been quite old. I'll see what flags seem to be missing from aliases.js and send a PR in.

**Comment by joshbeitler** [comment]
Just submitted #43 to address this.
