### ISSUE TITLE
Not in sync with emoji-mart

### ISSUE THREAD

**Issue by TheRav3n** [tommoor/react-emoji-render#47]
Is there a way to render the same emojis as in `emoji-mart`? Slack-style emoji names and unicodes are working, while emoticons produce different results.

For example `:*` here produces `:kissing:` where in `emoji-mart` it produces `:kissing_heart:`.

**Comment by enzoferey** [comment]
Hi @TheRav3n !

You can find our [`ascii aliases`](https://github.com/tommoor/react-emoji-render/blob/master/data/asciiAliases.js) file where we define such emojis mapping. I don't think changing the mapping is a good idea as it may potentially break the implementation of people relying on current mapping.

What is your use case so we can find a solution that works for all of us ?

**Comment by TheRav3n** [comment]
My use case is using `emoji-mart` (which is an emoji _picker_) for picking emoticons. Emoji Mart also displays to the user the corresponding emoticon, which I understand to be the same as in Facebook or Apple, so those should be somewhat standard. Then, I use `react-emoji-render` to actually render the emoticons. Their combinations can be found in those [JSON files](https://github.com/missive/emoji-mart/tree/master/data).

I understand that changing the implementation of `react-emoji-render` would be an issue. My suggestion would be to create an alternative `ascii aliases` file, matching `emoji-mart`, that can be used as an option.

Something like:

`<Emoji aliases="emoji-mart" text="This ❤️ sentence includes :+1: a variety of emoji types :)" />;`

I will probably end up forking and doing this myself. Question is: would you accept it as PR?

**Comment by enzoferey** [comment]
Thanks for the details. The problems about aliases is that they are not standard. `emoji-mart` and every other emoji library out there uses their own aliases. Just as an example, Slack and Github already uses different emoji aliases. I described the issue and how we are currently tackling it at https://github.com/tommoor/react-emoji-render/pull/41#issuecomment-552660375.

I'm not a huge fan of this solution you propose because it's pretty tied to the usage of `react-emoji-render` with `emoji-mart`, which means we need to keep in sync both libraries. But let's try to find a solution.

To give you context, we support ascii and non ascii aliases. Non ascii aliases have a solid pipeline where we can add as many [`custom ones`](https://github.com/tommoor/react-emoji-render/blob/master/data/aliases/customAliases.json) as we want. Ascii aliases only work as a translation towards non ascii aliases. They are less used nowadays and that's why they haven't received much attention in the last months. They don't follow the same data structure as aliases (keys are the result and values the matching part). But we can still add new ones quite easily via [this](https://github.com/tommoor/react-emoji-render/blob/master/data/asciiAliases.js) file.

Now, what I would consider interesting is to provide possibility of overriding our aliases or ascii aliases. By allowing users to pass their own object of aliases and ascii aliases they may override a key's value in our mappings. This brings the overhead of having to translate ascii aliases to the same data structure than aliases, but it should be straightforward to implement logic wise (spread both objects and that's it).

I'm not sure how often this feature might be used, but I think it doesn't add noise to the codebase as it's very located, and it doesn't add bundle size because it's just a spread operator. So if you want to see support for this @TheRav3n please feel free to open a PR as I described above or override the aliases with https://github.com/ds300/patch-package based on your needs 👍

**Comment by tommoor** [comment]
I wonder if we could diff the aliases between what we have and emoji_mart? Perhaps the differences are small – in which case it might be worth just baking in the additions

**Comment by enzoferey** [comment]
@tommoor what do you mean by "baking in" ? We can for sure add aliases they have that we don't, but the issue here is about aliases that mean different things for them than for us. So even if there is a very small amount of differences between us and them, we are still facing a break changing position if we replace them.

**Comment by TheRav3n** [comment]
I decided I will not be using `react-emoji-render` for now. This is due to the following:

- I would need it to parse a string containing HTML and to return a string containing HTML, instead of a component. This because I would need a pipeline of fuctions, converting text into HTML elements (for example, URLs).
- It doesn't match `emoji-mart` emoticons and it would require a PR to fix the issue.

I will probably work on a new npm module, in pure JS, handling this issue.

**Comment by enzoferey** [comment]
Thanks for the feedback @TheRav3n, I hope you will get your thing to work 👍 

By the way, we have a `toArray` function that allows html manipulation as you described, maybe it's interesting for you as an inspiration 😉
