### ISSUE TITLE
How to minimize bundle size?

### ISSUE THREAD

**Issue by anuraghazra** [tommoor/react-emoji-render#50]
Hi, thank you for this wonderful package. this works great but i'm just concerned about one thing, bundle size. i ran source-map-explorer on my app and found out that react-emoji-render is taking about 150kb of bundle size is there any way to fix this?

maybe treesake unused emojis from that [big aliases.js](https://github.com/tommoor/react-emoji-render/blob/master/data/aliases.js) file? 

![image](https://user-images.githubusercontent.com/35374649/75621970-178aa780-5bc1-11ea-8f86-bf74439ef717.png)

**Comment by enzoferey** [comment]
Hi @anuraghazra, thanks for opening the issue.

Unfortunately, I don't think we can really treeshake unused emojis on our side because all of them are potentially used by library users.

I have been googling around a bit and I don't know how you could treeshake this big file on user side neither. The technique is about statically detecting imports and only bundling those. Here, you are importing the whole dataset to check any potential input against it. Only thing I can think of is to provide a property to pass your own aliases so you can manually do the threeshaking 🤷‍♂ 

Maybe @tommoor does know about some technique?

**Comment by anuraghazra** [comment]
Maybe we can provide another package for those aliases? That would work I guess.

```npm i react-emoji-render-aliases```

Then user would have the flexibility to add their own aliases and if they want they can also include the official aliases. 

And the user who need only 6 or 7 emoji aliases they will not install that package and create their own aliases.json(js) file

🤔

**Comment by darryl-snow** [comment]
It would be nice if users were able to import only selected Emojis. I just found my bundle is 1.1mb so can't use this.

**Comment by tommoor** [comment]
The main selling point of this library is that it includes the aliases users would expect so I don't see a way it makes sense to remove them.

Don't forget the size is pre-compression – GZIP reduces this a lot. I would encourage you to always break up your bundle in production – webpack makes async chunk loading relatively painless.

**Comment by anuraghazra** [comment]
@tommoor you are probably right, well I ended up creating my own customized components..

```jsx
import React from 'react';

const TWEMOJIS: any = {
  ':+1:': '1f44d.svg',
  ':-1:': '1f44e.svg',
  ':heart:': '2764.svg',
  ':confused:': '1f615.svg',
  ':tada:': '1f389.svg',
  ':smile:': '1f604.svg'
};

const twemojiStyles = {
  width: '1em',
  height: '1em',
  margin: '0px 0.05em 0px 0.1em',
  verticalAlign: '-0.1em'
};
const Twemoji: React.FC<{ emoji: string; [x: string]: any }> = ({
  emoji,
  ...props
}) => {
  return (
    <img
      src={`http://twemoji.maxcdn.com/2/svg/${TWEMOJIS[emoji]}`}
      alt={'emoji'}
      style={twemojiStyles}
      {...props}
    />
  );
};


```

**Comment by tommoor** [comment]
Nice, for a very select subset of emojis this makes a lot of sense – thanks for sharing.
