### ISSUE TITLE
any way to turn off `:s` style emojis?

### ISSUE THREAD

**Issue by andycmaj** [tommoor/react-emoji-render#66]
```
import { toArray } from 'react-emoji-render';

// "Names must be lowercase, and can't contain spaces, periods, or most punctuation."
// -super helpful slack emoji name validation message
const SLACK_EMOJI_PATTERN = /:([\w+_-]+):\s?/gi;

export const renderEmojis = (value: string) => {
  const emojisArray = toArray(value)

  console.log(emojisArray);

  // toArray outputs React elements for emojis and strings for other
  const newValue = emojisArray.reduce<string>(
    (previous: string, current: string | React.ReactElement) => {
      if (typeof current === 'string') {
        // omit un-rendered emojis
        return previous + current.replace(SLACK_EMOJI_PATTERN, '');
      }
      return previous + (current.props.children as string);
    },
    ''
  );

  return newValue;
};

console.log(renderEmojis(
  ":stacked=\"isStackedGraph\"\r\n"
))
```

===> 

```
 😒tacked="isStackedGraph"
```

**Comment by enzoferey** [comment]
Hi @andycmaj ! Sorry for the late answer, did you find any solution to your issue ?

**Comment by NiiazalyDzhumaliev** [comment]
In the documentation written that you support ': smile:' like Slack. But a user is not able to type any text starting with "s". 

How can we fix it?

**Comment by enzoferey** [comment]
Hi @NiiazalyDzhumaliev. We do support Slack-like emoji style using colons yes. When writing `:s`, our emoji regex will match the bigger amount of text possible. That means if you write `:smile:` it will output "😄" and if you write `:swhatever` it will output "😒whatever".  You can see all the intentional design decisions in our [test file](https://github.com/tommoor/react-emoji-render/blob/master/src/__tests__/index-test.js#L127).

As written above, you could exclude certain string patterns from the `toArray` call as a solution. For example, if you want to ignore all ":s", you could write something like `.split(":s").map(toArray).join("s")`. Note that Slack-like emojis starting with `:s` would also be skipped.

Please feel free to share any other solution you might think about 👍🏻

**Comment by nickveliki** [comment]
> As written above, you could exclude certain string patterns from the toArray call as a solution. For example, if you want to ignore all ":s", you could write something like .split(":s").map(toArray).join(":s"). Note that Slack-like emojis starting with :s would also be skipped with this piece of code.

split(/(?<= ):s(?= )/) will only exclude :s  if it is standing alone...

**Comment by enzoferey** [comment]
Yes of course, thanks for the extra code @nickveliki :+1:

**Comment by enzoferey** [comment]
Closing as I consider this resolved. We might want to add in the future some way to toggle off ASCII emojis or certain emojis patterns, but as described at https://github.com/tommoor/react-emoji-render/issues/66#issuecomment-882088630, you can always work yourself around that.
